### ISSUE TITLE
why dont use remap script for the items

### ISSUE THREAD

**Issue by Rozaliya10** [BigBrotherTeam/BigBrother#114]
https://gist.github.com/7kasper/74c8abd9466aac41f56af2bc8a4e9594

its from protocolsupport dev but mey come i handy for you @hmy2001

**Comment by eternalharvest** [comment]
I'm not sure what is the remap script exactly, but I think it is not so simple...
We need bidirectional mapping and some item must be treated as entity instead of block.

Anyway, any suggestion is welcome.
Indeed, we may need to refactor the `ConvertUtils` class but i have no idea about that...

**Comment by 7kasper** [comment]
I'd wait till 1.13 comes around. Eventually you can just remap the runtimeID packet and remap a bit in the format (hopefully) Remapping blocks then you'd basically make a remap table with the minecraft:blah -> minecraft:blablab

**Comment by eternalharvest** [comment]
@Remu-2018, @7kasper 

I'm not sure whether if i am understanding the subject of this issue correctly.
But if u mean that we must use json/yml/xml format for these mapping data so that not depends on php code, i agree with it.

But we still need to consider about, exceptional case such as Trapdoor and Button.
Please refere to the following code.

https://github.com/BigBrotherTeam/BigBrother/blob/469d64ecde87429b8e5d13f1051068d116931fbd/src/shoghicp/BigBrother/utils/ConvertUtils.php#L787-L833

**Comment by 7kasper** [comment]
Yeah the change in data direction is absolute sh*t.
You shouldnt be using our script because you are remapping the other way around, but the end result can look very similar. With PE's new runtimeids you need to remap to PC blockstate. You can still make this into a static table. You just have to run the provided code a few times to generate it.
