### ISSUE TITLE
The received stringth length is longer than maximum allowed (29>16)

### ISSUE THREAD

**Issue by RUISMINEX** [BigBrotherTeam/BigBrother#115]
### Issue description

Im getting this error while logging in to the mcpe server via pc

here is console:

 [Server thread/INFO]: w4x51m[/197.224.203.47:56239] logged in with entity id 137 at (output1288, 2246, 128, 1965)
key: 53 Not implemented
key: 54 Not implemented
[12:18:47] [Server thread/INFO]: w4x51m[/197.224.203.47:56239] logged out due to Connection closed

**Comment by eternalharvest** [comment]
@TheCGaming 

Thank you for reporting the issue.
But I can't reproduce this issue...
Please use issue template and describe more about ur issue

At least please fill the prerequisite section of issue template like bellow
* PHP Version u are using
* GIT revision number of ur BigBrother codebase

Or just paste the log which is shown within BigBrother plugin startup
Some additional debug info was introduced by latest commit Latest commit 18f388939d9735eb1d5fd0ed401bdfed99de5ffd which make debugging more easier.

```
pmmp    | [13:25:44] [Server thread/INFO]: Enabling BigBrother v1.6.0-beta
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] PHP version: 7.2.0RC4
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] BigBrother revision: 1.6.0-dev-166-g954d4a9
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] Use openssl as AES encryption engine.
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] Use openssl as RSA encryption engine.
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] OpenSSL Library version: OpenSSL 1.0.2g  1 Mar 2016
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] OpenSSL Header version: OpenSSL 1.0.2g  1 Mar 2016
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] Server is being started in the background
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] Generating keypair
pmmp    | [13:25:44] [Server thread/INFO]: [BigBrother] Starting Minecraft: PC server on *:25565 version 1.12.2
```

And if u can reproduce this issue, please describe the step to reproduce this issue.

**Comment by thelucyclub** [comment]
@eternalharvest To reproduce:
1. be the first person in a test server (PC)
2. join on MCPE (up to 3 times)
3. the error occurs, even if you're no longer online (MCPE)

**Comment by eternalharvest** [comment]
@thelucyclub 

Thank u for describing how to reproduce this issue.
But I can't reproduce this issue...

Please use latest master of BigBrother and paste your startup log of BigBrother plugin so that we can debug it easily.

Regards.

**Comment by thelucyclub** [comment]
@eternalharvest 

```
[12:54:42] [Server thread/INFO]: [BigBrother] OS: Windows NT MCPE-SERVER 10.0 build 16299 (Windows 10) AMD64
[12:54:42] [Server thread/INFO]: [BigBrother] PHP version: 7.2.1
[12:54:42] [Server thread/INFO]: [BigBrother] PMMP version: 1.7dev [REDACTED]
[12:54:42] [Server thread/INFO]: [BigBrother] PMMP Server version: v1.2.13
[12:54:42] [Server thread/INFO]: [BigBrother] PMMP API version: 3.0.0-ALPHA11
[12:54:42] [Server thread/INFO]: [BigBrother] Use openssl as AES encryption engine.
[12:54:42] [Server thread/INFO]: [BigBrother] Use openssl as RSA encryption engine.
[12:54:42] [Server thread/INFO]: [BigBrother] OpenSSL Library version: OpenSSL 1.1.0g  2 Nov 2017
[12:54:42] [Server thread/INFO]: [BigBrother] OpenSSL Header version: OpenSSL 1.1.0g  2 Nov 2017
[12:54:42] [Server thread/INFO]: [BigBrother] Server is being started in the background
[12:54:42] [Server thread/INFO]: [BigBrother] Generating keypair
[12:54:42] [Server thread/INFO]: [BigBrother] Starting Minecraft: PC server on *:25565 version 1.12.2
```

**Comment by eternalharvest** [comment]
@thelucyclub 

Thank u for reporting the detail.
According to ur first report, it seems some metadata conversion is not implemented yet...
I'm not sure what is the exact cause of this issue, but i think this issue is comes from `EntityMetadataPacket` i think...

@hmy2001 seems improving `ConvertUtils::convertPEToPCMetadata()` utility method, but key 53 and 54 is not implemented yet. These metadata keys are defined in `Entity` class of pmmp (please refer to the following link).

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Entity.php#L145-L146

And Key 54 is defined as `DATA_BOUNDING_BOX_WIDTH` but 53 is unknown.
I think this issue can be fixed if this metadata conversion method is properly implemented.

**Comment by thelucyclub** [comment]
@eternalharvest Thank you for the diagnosis. I hope this issue is fixed soon, many of my users cant play right now 😞

**Comment by thelucyclub** [comment]
Because `BOUNDING_BOX` is not implanted in Java Edition, is it possible for entities to just be removed on the client?

**Comment by thelucyclub** [comment]
@eternalharvest 

14:26:19 | bkr | Connecting to 192.168.20.27, 25565
-- | -- | --
14:26:23 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Default value cannot be lower than minimum value! 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.IllegalArgumentException: Default value cannot be lower than minimum value! 	at wj.<init>(SourceFile:21) 	at brz.a(SourceFile:1744) 	at kv.a(SourceFile:70) 	at kv.a(SourceFile:15) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:23 | j | Loaded 1 advancements
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:638) 	at je.a(SourceFile:96) 	at je.a(SourceFile:18) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1078) 	at ii.a(SourceFile:45) 	at ii.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1078) 	at ii.a(SourceFile:45) 	at ii.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:638) 	at je.a(SourceFile:96) 	at je.a(SourceFile:18) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:638) 	at je.a(SourceFile:96) 	at je.a(SourceFile:18) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:638) 	at je.a(SourceFile:96) 	at je.a(SourceFile:18) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:638) 	at je.a(SourceFile:96) 	at je.a(SourceFile:18) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:638) 	at je.a(SourceFile:96) 	at je.a(SourceFile:18) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:588) 	at jq.a(SourceFile:57) 	at jq.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bjb | [CHAT] {%0} joined the game
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1003) 	at is.a(SourceFile:50) 	at is.a(SourceFile:12) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bjb | [CHAT] ======================\n\nWelcome to Hebby MCPE\n\n======================
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bjb | [CHAT] » JuniorPopsicle
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:482) 	at ic.a(SourceFile:67) 	at ic.a(SourceFile:14) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:504) 	at kt.a(SourceFile:55) 	at kt.a(SourceFile:9) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1063) 	at kg.a(SourceFile:40) 	at kg.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at jx.a(SourceFile:42) 	at brz.a(SourceFile:558) 	at jx.a(SourceFile:38) 	at jx.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1063) 	at kg.a(SourceFile:40) 	at kg.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1063) 	at kg.a(SourceFile:40) 	at kg.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1063) 	at kg.a(SourceFile:40) 	at kg.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:1063) 	at kg.a(SourceFile:40) 	at kg.a(SourceFile:10) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more
14:26:24 | bib | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at h.a(SourceFile:47) 	at bib.az(SourceFile:991) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) Caused by: java.lang.NullPointerException 	at brz.a(SourceFile:468) 	at kd.a(SourceFile:42) 	at kd.a(SourceFile:11) 	at hv$1.run(SourceFile:13) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at h.a(SourceFile:46) 	... 3 more

**Comment by eternalharvest** [comment]
@thelucyclub 

hmm...
Sorry, I don't understand why NullPointerException happens...
It seems client crash after login for some reasons but I don't know why.

**Comment by HerryYT** [comment]
also now i restarted server and it works again

**Comment by thelucyclub** [comment]
@HerryYT The problem is caused by NPCs (Slapper) that use DATA_BOUNDING_BOX which is not implented on MCJE (yet..?)

**Comment by HerryYT** [comment]
Really not, I wasn't having slapper plugin

**Comment by eternalharvest** [comment]
@RUISMINEX, @thelucyclub, @HerryYT

When I was debugging another issue, I found something strange which may related to this issue.
Please tell me ur username or length of ur username which cause this issue.
I think this issue is related to the length of username (Maximum: 16 bytes)

**Comment by KingRainbow44** [comment]
This issue is the username. If it is over 16 bytes, then you will be kicked. This is a Java limitation and why servers like Hypixel use two armor stands in their lobbies instead of 1.
