### ISSUE TITLE
How long could it take for a dev to add crafting

### ISSUE THREAD

**Issue by NormalOcean6686** [BigBrotherTeam/BigBrother#156]
Hey I was woundering if u can give me a estmation of how long would it take to add crafting support? I want my server to have this with crafting support.I want my devs to work on it. But I don't know if I feel it is worth it if Idk how long it will take

**Comment by eternalharvest** [comment]
@NormalOcean6686 

Thank u for ur consideration about ur contribution!
But I think it is difficult to estimate how long it would take to support crafting feature exactly.

If I assume your employee has familiar with the code base of PMMP and BigBrother, I roughly guess it would be more than at least 1 man-month with full-time employee.
I think it depends on your requirements.

Since crafting feature is highly related to the inventory / inventory operation (transaction), It is difficult to complete these tasks related to crafting.
And If u wish ur user can't cheat, implementation costs will increase more and more!!

We can not afford to complete these work right now or in the future.
But we are welcome any type of contribution!

**Comment by NormalOcean6686** [comment]
OK thanks
