### ISSUE TITLE
Crash when joining the server

### ISSUE THREAD

**Issue by Misteboss** [BigBrotherTeam/BigBrother#47]
### Issue description
When I join my serverI have this error and then my server crash

### How to reproduce
Join the server.

### Server log(crash dump)
![capture d ecran 2017-06-28 a 20 10 21](https://user-images.githubusercontent.com/17687222/27654547-c07e3770-5c42-11e7-9c72-01a974a8acb6.png)

**Comment by eternalharvest** [comment]
at least, plz describe the BigBrother version or revision (git commit id) u are using in the **Prerequisite** section. And I think u are using ur own fork of PocketMine-MP, plz try any other PocketMine-MP compatible server (we recommends tesseract or pmmp). plz report more specific description if same problem was occur with another version of PocketMine-MP.

it seems BigBrother plugin's code base is not latest, or u are using different fork of BigBrother plugin. because, zlib_decode() function call are not located at line 1612 (currently at line 1622).

**Comment by caspervanneck** [comment]
@hmy2001 same problem like me

**Comment by caspervanneck** [comment]
he need to use latest binarys

**Comment by Misteboss** [comment]
I am using the last version of Pocketmine and of BigBrother (master branch).
@caspervanneck What I need to do to fix it ?

**Comment by Misteboss** [comment]
My PHP binaries are up to date, 7.0.2 reopen it please.

**Comment by Driesboy** [comment]
php binarys i think

**Comment by Driesboy** [comment]
7.0.20 is the newest btw

**Comment by Misteboss** [comment]
I HAVE no problem with PM... And PM is usisng zlib_decode() so.. I don’t understand why you close it..

**Comment by caspervanneck** [comment]
@Misteboss test it first then i open it

**Comment by hmy2001** [comment]
Please tell me var_dump($packet); in line 1611(1621).

**Comment by eternalharvest** [comment]
Sorry, my previous post is wrong (the Translator.php of my BigBrother was dirty).
The function `zlib_decode()` is located at line 1612 exactly.

But I can't reproduce this error with latest ppmp on following php version.
```
PHP 7.0.3 (cli) (built: Feb  7 2016 21:08:57) ( ZTS )                                                                                                                                                       
Copyright (c) 1997-2016 The PHP Group                                                                                                                                                                       
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies 
```

**Comment by Misteboss** [comment]
You should add a check to the payload field to see if he is empty
![capture d ecran 2017-06-30 a 19 38 03](https://user-images.githubusercontent.com/17687222/27747498-ac2d29cc-5dcb-11e7-93e6-48a9801a3084.png)

**Comment by Misteboss** [comment]
I added a check to don't decode it if payload is null and now I have this error :/
![capture d ecran 2017-06-30 a 19 40 34](https://user-images.githubusercontent.com/17687222/27747582-12e47d3c-5dcc-11e7-8f55-edcdff11db28.png)

**Comment by Misteboss** [comment]
I tried with the last version same issue. And with or without plugins.

**Comment by eternalharvest** [comment]
I'm not sure why `BatchPacket#payload` is `NULL`.
Since `offset` is 0 and it seems `buffer` remains some string in, I think it's because BatchPacket is not decoded.

Even though I replace the zlib_decode() to force return null or insert `throw new ErrorException()` beforce zlib_decode() call, I could'nt reproduce the screenshot that you post.
I think we need more info.

**Comment by eternalharvest** [comment]
I think `BatchPacket#payload` must be decoded, before zlib_decode() is called.
I mean `BatchPacket#decode()` must be called.
Since offset is 0 and buffer remains some string value in, I think it's because `BatchPacket#decode()` is not called.

Anyway, I can't reproduce your screenshot even if I replace the `zlib_decode()` to force return null.
It seems strange...

**Comment by Misteboss** [comment]
api3\blocks

**Comment by eternalharvest** [comment]
please try to replace try block at line 1622 as follows.
and plz tell me the result of stack trace.

https://github.com/BigBrotherTeam/BigBrother/blob/b59f6c523368dda741c8738a159840f71a04b71f/src/shoghicp/BigBrother/network/Translator.php#L1622-L1626

```php
try {
    $str = \zlib_decode($packet->payload, 1024 * 1024 * 64); //Max 64MB
}catch (\ErrorException $e){
    echo $e->getTraceAsString()."\n";
    exit();
}
```

**Comment by Misteboss** [comment]
I have no output :/. Thre good version to use is 1.12 right ?

**Comment by eternalharvest** [comment]
I'm using Minecraft 1.12 PC edition as client.

**Comment by Misteboss** [comment]
I don't understand, I am using the latest version.. do you want to try ?

**Comment by eternalharvest** [comment]
how to try?
i think it is not client related problem though...

**Comment by SuperMaXAleX** [comment]
Plugins are the cause.

**Comment by SuperMaXAleX** [comment]
Packets & functionalities haven't been totally converted or implanted.

**Comment by Misteboss** [comment]
Fixed with an other MCPC client and the same version can't understand
